/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Exam {
  'minAccuracy' : bigint,
  'name' : string,
  'description' : string,
  'language' : { 'hindi' : null } |
    { 'bilingual' : null } |
    { 'english' : null },
  'requiredWPM' : bigint,
  'timeLimitMinutes' : bigint,
  'category' : string,
  'authority' : string,
  'officialWebsite' : string,
}
export interface Passage {
  'id' : string,
  'content' : string,
  'wordCount' : bigint,
  'difficulty' : bigint,
  'category' : string,
}
export type Time = bigint;
export interface TypingResult {
  'wpm' : bigint,
  'user' : Principal,
  'errors' : bigint,
  'timestamp' : Time,
  'examId' : string,
  'sessionId' : string,
  'timeTaken' : bigint,
  'passed' : boolean,
  'accuracy' : bigint,
}
export interface _SERVICE {
  'getAllExams' : ActorMethod<[], Array<Exam>>,
  'getAllPassages' : ActorMethod<[], Array<Passage>>,
  'getExam' : ActorMethod<[string], Exam>,
  'getExamResults' : ActorMethod<[string], Array<TypingResult>>,
  'getMyResults' : ActorMethod<[], Array<TypingResult>>,
  'getPassage' : ActorMethod<[string], Passage>,
  'getPassagesByCategory' : ActorMethod<[string], Array<Passage>>,
  'getSessionResult' : ActorMethod<[string], TypingResult>,
  'submitResult' : ActorMethod<
    [string, string, bigint, bigint, bigint, bigint, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];