/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Exam = IDL.Record({
  'minAccuracy' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'language' : IDL.Variant({
    'hindi' : IDL.Null,
    'bilingual' : IDL.Null,
    'english' : IDL.Null,
  }),
  'requiredWPM' : IDL.Nat,
  'timeLimitMinutes' : IDL.Nat,
  'category' : IDL.Text,
  'authority' : IDL.Text,
  'officialWebsite' : IDL.Text,
});
export const Passage = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'wordCount' : IDL.Nat,
  'difficulty' : IDL.Nat,
  'category' : IDL.Text,
});
export const Time = IDL.Int;
export const TypingResult = IDL.Record({
  'wpm' : IDL.Nat,
  'user' : IDL.Principal,
  'errors' : IDL.Nat,
  'timestamp' : Time,
  'examId' : IDL.Text,
  'sessionId' : IDL.Text,
  'timeTaken' : IDL.Nat,
  'passed' : IDL.Bool,
  'accuracy' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllExams' : IDL.Func([], [IDL.Vec(Exam)], ['query']),
  'getAllPassages' : IDL.Func([], [IDL.Vec(Passage)], ['query']),
  'getExam' : IDL.Func([IDL.Text], [Exam], ['query']),
  'getExamResults' : IDL.Func([IDL.Text], [IDL.Vec(TypingResult)], ['query']),
  'getMyResults' : IDL.Func([], [IDL.Vec(TypingResult)], ['query']),
  'getPassage' : IDL.Func([IDL.Text], [Passage], ['query']),
  'getPassagesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Passage)], ['query']),
  'getSessionResult' : IDL.Func([IDL.Text], [TypingResult], ['query']),
  'submitResult' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Exam = IDL.Record({
    'minAccuracy' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'language' : IDL.Variant({
      'hindi' : IDL.Null,
      'bilingual' : IDL.Null,
      'english' : IDL.Null,
    }),
    'requiredWPM' : IDL.Nat,
    'timeLimitMinutes' : IDL.Nat,
    'category' : IDL.Text,
    'authority' : IDL.Text,
    'officialWebsite' : IDL.Text,
  });
  const Passage = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'wordCount' : IDL.Nat,
    'difficulty' : IDL.Nat,
    'category' : IDL.Text,
  });
  const Time = IDL.Int;
  const TypingResult = IDL.Record({
    'wpm' : IDL.Nat,
    'user' : IDL.Principal,
    'errors' : IDL.Nat,
    'timestamp' : Time,
    'examId' : IDL.Text,
    'sessionId' : IDL.Text,
    'timeTaken' : IDL.Nat,
    'passed' : IDL.Bool,
    'accuracy' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllExams' : IDL.Func([], [IDL.Vec(Exam)], ['query']),
    'getAllPassages' : IDL.Func([], [IDL.Vec(Passage)], ['query']),
    'getExam' : IDL.Func([IDL.Text], [Exam], ['query']),
    'getExamResults' : IDL.Func([IDL.Text], [IDL.Vec(TypingResult)], ['query']),
    'getMyResults' : IDL.Func([], [IDL.Vec(TypingResult)], ['query']),
    'getPassage' : IDL.Func([IDL.Text], [Passage], ['query']),
    'getPassagesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Passage)],
        ['query'],
      ),
    'getSessionResult' : IDL.Func([IDL.Text], [TypingResult], ['query']),
    'submitResult' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };