/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TypingResult {
    wpm: bigint;
    user: Principal;
    errors: bigint;
    timestamp: Time;
    examId: string;
    sessionId: string;
    timeTaken: bigint;
    passed: boolean;
    accuracy: bigint;
}
export type Time = bigint;
export interface Passage {
    id: string;
    content: string;
    wordCount: bigint;
    difficulty: bigint;
    category: string;
}
export interface Exam {
    minAccuracy: bigint;
    name: string;
    description: string;
    language: Variant_hindi_bilingual_english;
    requiredWPM: bigint;
    timeLimitMinutes: bigint;
    category: string;
    authority: string;
    officialWebsite: string;
}
export enum Variant_hindi_bilingual_english {
    hindi = "hindi",
    bilingual = "bilingual",
    english = "english"
}
export interface backendInterface {
    getAllExams(): Promise<Array<Exam>>;
    getAllPassages(): Promise<Array<Passage>>;
    getExam(examId: string): Promise<Exam>;
    getExamResults(examId: string): Promise<Array<TypingResult>>;
    getMyResults(): Promise<Array<TypingResult>>;
    getPassage(passageId: string): Promise<Passage>;
    getPassagesByCategory(category: string): Promise<Array<Passage>>;
    getSessionResult(sessionId: string): Promise<TypingResult>;
    submitResult(sessionId: string, examId: string, wpm: bigint, accuracy: bigint, errors: bigint, timeTaken: bigint, passed: boolean): Promise<void>;
}
import type { Exam as _Exam } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllExams(): Promise<Array<Exam>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExams();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExams();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPassages(): Promise<Array<Passage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPassages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPassages();
            return result;
        }
    }
    async getExam(arg0: string): Promise<Exam> {
        if (this.processError) {
            try {
                const result = await this.actor.getExam(arg0);
                return from_candid_Exam_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExam(arg0);
            return from_candid_Exam_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExamResults(arg0: string): Promise<Array<TypingResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExamResults(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExamResults(arg0);
            return result;
        }
    }
    async getMyResults(): Promise<Array<TypingResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyResults();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyResults();
            return result;
        }
    }
    async getPassage(arg0: string): Promise<Passage> {
        if (this.processError) {
            try {
                const result = await this.actor.getPassage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPassage(arg0);
            return result;
        }
    }
    async getPassagesByCategory(arg0: string): Promise<Array<Passage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPassagesByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPassagesByCategory(arg0);
            return result;
        }
    }
    async getSessionResult(arg0: string): Promise<TypingResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionResult(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionResult(arg0);
            return result;
        }
    }
    async submitResult(arg0: string, arg1: string, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitResult(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitResult(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
}
function from_candid_Exam_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Exam): Exam {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    minAccuracy: bigint;
    name: string;
    description: string;
    language: {
        hindi: null;
    } | {
        bilingual: null;
    } | {
        english: null;
    };
    requiredWPM: bigint;
    timeLimitMinutes: bigint;
    category: string;
    authority: string;
    officialWebsite: string;
}): {
    minAccuracy: bigint;
    name: string;
    description: string;
    language: Variant_hindi_bilingual_english;
    requiredWPM: bigint;
    timeLimitMinutes: bigint;
    category: string;
    authority: string;
    officialWebsite: string;
} {
    return {
        minAccuracy: value.minAccuracy,
        name: value.name,
        description: value.description,
        language: from_candid_variant_n4(_uploadFile, _downloadFile, value.language),
        requiredWPM: value.requiredWPM,
        timeLimitMinutes: value.timeLimitMinutes,
        category: value.category,
        authority: value.authority,
        officialWebsite: value.officialWebsite
    };
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hindi: null;
} | {
    bilingual: null;
} | {
    english: null;
}): Variant_hindi_bilingual_english {
    return "hindi" in value ? Variant_hindi_bilingual_english.hindi : "bilingual" in value ? Variant_hindi_bilingual_english.bilingual : "english" in value ? Variant_hindi_bilingual_english.english : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Exam>): Array<Exam> {
    return value.map((x)=>from_candid_Exam_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
